# Generated by Django 3.2.9 on 2021-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
