# Generated by Django 3.2.9 on 2022-01-02 09:55

from django.db import migrations, models
import restaur.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='homeImage',
            field=models.ImageField(default='media/resto/defaultHome.jpeg', upload_to=restaur.models.upload_to, verbose_name='image'),
        ),
    ]
