# Generated by Django 3.2.9 on 2021-12-26 09:55

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='thumbnail',
            field=models.ImageField(upload_to=dishes.models.uploadThumbnail, verbose_name='image'),
        ),
    ]
