# Generated by Django 3.2.9 on 2022-01-02 12:20

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='homeImage',
            field=models.ImageField(null=True, upload_to=dishes.models.uploadThumbnail, verbose_name='image'),
        ),
    ]
