# Generated by Django 3.2.9 on 2022-01-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_dish_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='homeImage',
        ),
    ]
